add_newline = false

[character]
style_success = "fg:cyan"
style_failure = "fg:cyan"
symbol = "ğº"

[directory]
style = "fg:purple"
truncation_length = 6

[cmd_duration]
disabled = true

[jobs]
disabled = true
