add_newline = false

[character]
success_symbol = "[ğº](bold red)"
error_symbol = "[ğº](bold red)"

[directory]
format = "[$path](bold purple) "
truncation_length = 6

[cmd_duration]
disabled = true

[jobs]
disabled = true